imagePullSecrets: []

dockerconfigjson: ""

podSecurityContext:
  enabled: true
  fsGroup: 2000

securityContext:
  enabled: true
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

applicationContainer:
  image: {}
  env: []

probe: {}

service: []

hostAliases: []

resources:
  limits: {}
  requests: {}

annotations:
  prometheus: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

secrets: []
