{{ if .Values.secrets }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
type: {{ .secret.type }}
data:
  {{ range $data := .secret.data }}
  {{ .key }}: | 
{{ .value | indent 4 }}
  {{ end }}
{{- end  }}
{{  end  }}