name: 'Push to App Catalog'

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_app_catalog:
    uses: giantswarm/app-build-suite/.github/workflows/push-to-app-catalog.yaml@v1.1.2
    with:
      app_catalog: babylon-app-catalog
      chart: gateway
      organization: TheHutGroup
    secrets:
      envPAT: ${{ secrets.WORKFLOW_WRITE }}
